### ISSUE TITLE
question

### ISSUE THREAD

**Issue by SergeyCPP14634** [GameHerobrine/relique-assets#2]
hello GameHerobrine, could you give me the source code of relique 0.3 pre 3 fix 1. I want to introduce a couple of modifications to it. If anything, here is the mail: sikorenkosergej@gmail.com. I am a friend of freehij and wrote a fly and sprint for alpha 1.2.3_04

**Comment by GameHerobrine** [comment]
i dont have source code of old relique versions

**Comment by SergeyCPP14634** [comment]
Okay then, can you send me the latest client sources at .zip

вт, 25 июн. 2024 г., 07:39 GameHerobrine ***@***.***>:

**Comment by GameHerobrine** [comment]
latest - no

**Comment by SergeyCPP14634** [comment]
In general, any source code is simply your client the best, I don’t see the
point in rewriting mine from scratch, I want to use your source code and
add a lot bypass

вт, 25 июн. 2024 г., 18:38 GameHerobrine ***@***.***>:
