### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SergeyCPP14634** [GameHerobrine/relique-assets#3]
Do you know about the client bug when logging into the server with your cheat?. If you don't mind, please send me a link to the sources of any version at all

**Comment by GameHerobrine** [comment]
> about the client bug when logging into the server with your cheat

with multiversion - yes, with intended version(b1.7.3) - no

> please send me a link to the sources of any version at all

the only src i have is latest, which i dont want to send

**Comment by SergeyCPP14634** [comment]
Ok got it brother :)

ср, 26 июн. 2024 г., 07:06 GameHerobrine ***@***.***>:
